<?php

namespace TrainBundle\Repository;

/**
 * DiscountCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscountCardRepository extends \Doctrine\ORM\EntityRepository
{
}
