<?php

namespace TrainBundle\Repository;

/**
 * OrderTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTripRepository extends \Doctrine\ORM\EntityRepository
{
}
