<?php

namespace TrainBundle\Repository;

/**
 * StationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends \Doctrine\ORM\EntityRepository
{
}
