<?php

namespace TrainBundle\Repository;

/**
 * UserCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCardRepository extends \Doctrine\ORM\EntityRepository
{
}
